driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: ubuntu-14.04
  - name: debian-7.10

suites:
  - name: default
    run_list:
      - recipe[libuuid-user::default]
      - recipe[libuuid-user::verify]
    attributes:
